export enum TypeOrigineCreationCategorieCahierDeTexte {
	OCCCDT_Utilisateur = 0,
	OCCCDT_Pre_Cours = 1,
	OCCCDT_Pre_Correction = 2,
	OCCCDT_Pre_Devoir = 3,
	OCCCDT_Pre_Interro = 4,
	OCCCDT_Pre_TD = 5,
	OCCCDT_Pre_TP = 6,
	OCCCDT_Pre_Evaluation = 7,
	OCCCDT_Pre_EPI = 8,
	OCCCDT_Pre_AP = 9,
	OCCCDT_Pre_Mod_Peda_Oral = 10,
	OCCCDT_Pre_Mod_Peda_Ecrit = 11,
	OCCCDT_Pre_LienVisio = 12,
	OCCCDT_Pre_CCF = 13,
	OCCCDT_Pre_EC = 14,
}
